In [ ]:
import pandas as pd
from pathlib import Path
print(sorted(p.name for p in Path("dados").glob("*.csv")))

1. Diagnóstico dos arquivos

In [2]:
maio=pd.read_csv("dados/chamados_2026_05.csv")
maio.head()

,id_chamado,data_abertura,data_fechamento,categoria,cliente,tecnico,prioridade,horas_gastas,custo_total
0,1000,2026-05-11,2026-05-12,Acesso,Alfa Log,Ana Ribeiro,Baixa,5.4,260.96
1,1001,2026-05-17,2026-05-18,Rede,Beta Telecom,Diego Prado,Critica,1.4,363.02
2,1002,2026-05-14,2026-05-14,Telefonia,Beta Telecom,Bruno Tavares,Baixa,8.3,1317.64
3,1003,2026-05-08,2026-05-08,Telefonia,Cedro Varejo,Carla Menezes,Critica,2.4,447.51
4,1004,2026-05-10,2026-05-14,Hardware,Beta Telecom,Elisa Fontes,Media,5.5,1788.96

In [3]:
maio.shape #diz quantas linhas e colunas tem

(85, 9)

In [4]:
maio.info() #quantas linhas tem, e pra cada coluna o nome, quantos valores não nulos e o tipo(int64,float64,str...)
#se tem 85 linhas e todas as colunas mostram 85 non-null, quer dizer que estão todas preenchidas.

<class 'pandas.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_chamado       85 non-null     int64
 1   data_abertura    85 non-null     str
 2   data_fechamento  85 non-null     str
 3   categoria        85 non-null     str
 4   cliente          85 non-null     str
 5   tecnico          85 non-null     str
 6   prioridade       85 non-null     str
 7   horas_gastas     85 non-null     float64
 8   custo_total      85 non-null     float64
dtypes: float64(2), int64(1), str(6)
memory usage: 10.8 KB

In [5]:
junho=pd.read_csv("dados/chamados_2026_06.csv")
junho.head() #os erros que percebi: colunas com nomes diferentes, datas em dia/mês/ano em vez de ano-mês-dia

,ID,Data Abertura,Data Fechamento,Tipo,Cliente,Responsavel,Prioridade,Horas,Custo (R$)
0,2000,21/06/2026,22/06/2026,Hardware,Ere Servicos,Diego Prado,Alta,3.1,1244.85
1,2001,14/06/2026,14/06/2026,Acesso,Delta Industria,Ana Ribeiro,Baixa,13.1,1361.96
2,2002,20/06/2026,26/06/2026,Hardware,Ere Servicos,Diego Prado,Baixa,12.8,1796.34
3,2003,06/06/2026,09/06/2026,Acesso,Fenix Energia,Carla Menezes,Alta,4.0,2384.89
4,2004,21/06/2026,23/06/2026,Acesso,Delta Industria,Carla Menezes,Critica,8.0,1310.43

In [6]:
#abriu direito? Sim
#Sinal de problema: Número de colunas absurdo-> separador errado
junho.shape

(92, 9)

In [7]:
#Os nomes batem com o padrão? tem nomes diferentes
#Sinal de problema: Nome diferente ou espaço sobrando
junho.columns

Index(['ID', 'Data Abertura', 'Data Fechamento', 'Tipo', 'Cliente',
       'Responsavel', 'Prioridade', 'Horas', 'Custo (R$)'],
      dtype='str')

In [8]:
#Os tipos estao certos? Sim
#Sinal de problema: Número que veio como texto->tem sujeira dentro
junho.info()

<class 'pandas.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               92 non-null     int64
 1   Data Abertura    92 non-null     str
 2   Data Fechamento  92 non-null     str
 3   Tipo             92 non-null     str
 4   Cliente          92 non-null     str
 5   Responsavel      92 non-null     str
 6   Prioridade       92 non-null     str
 7   Horas            92 non-null     float64
 8   Custo (R$)       92 non-null     float64
dtypes: float64(2), int64(1), str(6)
memory usage: 11.7 KB

In [9]:
#Falta alguma coisa? Não, nao tem NA´s
#Sinal de problema: Tiver acima de 0
junho.isna().sum()

ID                 0
Data Abertura      0
Data Fechamento    0
Tipo               0
Cliente            0
Responsavel        0
Prioridade         0
Horas              0
Custo (R$)         0
dtype: int64

In [10]:
#Tem linha repetida? Não
#isso descubro se tiver qualquer número acima de 0. Se tiver, tem
junho.duplicated().sum()

np.int64(0)

In [11]:
#Os textos são consistentes? Sim
#Sinal de problema: mesma coisa escrita de 2 jeitos, ou valor fora do dominio 
junho.value_counts()

ID    Data Abertura  Data Fechamento  Tipo       Cliente          Responsavel    Prioridade  Horas  Custo (R$)
2000  21/06/2026     22/06/2026       Hardware   Ere Servicos     Diego Prado    Alta        3.1    1244.85       1
2001  14/06/2026     14/06/2026       Acesso     Delta Industria  Ana Ribeiro    Baixa       13.1   1361.96       1
2002  20/06/2026     26/06/2026       Hardware   Ere Servicos     Diego Prado    Baixa       12.8   1796.34       1
2003  06/06/2026     09/06/2026       Acesso     Fenix Energia    Carla Menezes  Alta        4.0    2384.89       1
2004  21/06/2026     23/06/2026       Acesso     Delta Industria  Carla Menezes  Critica     8.0    1310.43       1
                                                                                                                 ..
2087  04/06/2026     06/06/2026       Software   Alfa Log         Carla Menezes  Critica     9.8    2941.90       1
2088  09/06/2026     11/06/2026       Hardware   Beta Telecom     Elisa Fontes   Baixa       2.8    2902.67       1
2089  27/06/2026     28/06/2026       Hardware   Cedro Varejo     Carla Menezes  Media       12.4   1105.09       1
2090  08/06/2026     11/06/2026       Telefonia  Horizonte Bank   Diego Prado    Baixa       12.1   1444.11       1
2091  24/06/2026     25/06/2026       Telefonia  Ere Servicos     Bruno Tavares  Critica     8.9    322.74        1
Name: count, Length: 92, dtype: int64

In [12]:
#Os números fazem sentido?
#Sinal de problema: negativo onde não pode, ou max absurdo
junho.describe()

               ID      Horas   Custo (R$)
count    92.00000  92.000000    92.000000
mean   2045.50000   6.944565  1593.180978
std      26.70206   3.877446   856.304549
min    2000.00000   0.500000   178.180000
25%    2022.75000   3.600000   949.095000
50%    2045.50000   6.200000  1452.255000
75%    2068.25000  10.075000  2162.595000
max    2091.00000  13.900000  3163.910000

In [13]:
junho.columns= junho.columns.str.strip() #esse .strip corta os espaços do começo e dp fim de um texto
#.str significa: faça isso em cada item da lista, um por um

In [14]:
julho=pd.read_csv("dados/chamados_2026_07.csv",sep=";")
julho.head() #está uma bagunça. não separou as colunas, não excluiu os ponto e virgula,...

,ID,Data Abertura,Data Fechamento,Tipo,Cliente,Responsavel,Prioridade,Horas,Custo (R$)
0,3022,07/07/2026,10/07/2026,Acesso,Alfa Log,Ana Ribeiro,Critica,"12,0","1441,97"
1,3030,19/07/2026,22/07/2026,Telefonia,Delta Industria,Diego Prado,Baixa,"9,1","2666,43"
2,3010,27/07/2026,28/07/2026,Acesso,Fenix Energia,Elisa Fontes,Alta,"8,3","575,75"
3,3028,22/07/2026,27/07/2026,Hardware,Fenix Energia,Ana Ribeiro,Critica,"11,7","2913,56"
4,3005,21/07/2026,22/07/2026,Software,Fenix Energia,Carla Menezes,Critica,"4,0","1174,81"

In [15]:
julho.shape #tem 89 linhas e apenas uma coluna e o separador de ; está errado

(89, 9)

In [16]:
julho.columns #nomes estão certos mas tem a questão do espaçamento.

Index(['ID', 'Data Abertura', 'Data Fechamento', 'Tipo', 'Cliente',
       'Responsavel', 'Prioridade', 'Horas', 'Custo (R$)'],
      dtype='str')

In [17]:
julho.info() #numero veio como texto, então tem sujeira dentro

<class 'pandas.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               89 non-null     int64
 1   Data Abertura    89 non-null     str
 2   Data Fechamento  83 non-null     str
 3   Tipo             89 non-null     str
 4   Cliente          89 non-null     str
 5   Responsavel      81 non-null     str
 6   Prioridade       89 non-null     str
 7   Horas            89 non-null     str
 8   Custo (R$)       88 non-null     str
dtypes: int64(1), str(8)
memory usage: 12.0 KB

In [18]:
julho.isna().sum() #é diferente de 0

ID                 0
Data Abertura      0
Data Fechamento    6
Tipo               0
Cliente            0
Responsavel        8
Prioridade         0
Horas              0
Custo (R$)         1
dtype: int64

In [19]:
julho.duplicated().sum()

np.int64(11)

julho.value_counts()

In [20]:
julho.describe()

                ID
count    89.000000
mean   3038.393258
std      22.633753
min    3000.000000
25%    3019.000000
50%    3038.000000
75%    3058.000000
max    3077.000000

In [21]:
agosto=pd.read_csv("dados/chamados_2026_08.csv")
agosto.head() #horas negativas, as datas estão do formato brasileiro mas deveriam estar ano-mes-dia, na coluna tipo, tem telefonia e Telefonia

,ID,Data Abertura,Data Fechamento,Tipo,Cliente,Responsavel,Prioridade,Horas,Custo (R$)
0,4000,20/08/2026,24/08/2026,Software,Beta Telecom,Diego Prado,Media,6.4,1676.29
1,4001,10/08/2026,13/08/2026,Telefonia,Ere Servicos,Carla Menezes,Media,-10.4,2390.06
2,4002,10/08/2026,16/08/2026,Acesso,Delta Industria,Diego Prado,Media,7.9,1224.46
3,4003,18/08/2026,20/08/2026,telefonia,Horizonte Bank,Diego Prado,Alta,0.9,1121.04
4,4004,07/08/2026,11/08/2026,Telefonia,Gama Saude,Elisa Fontes,Critica,0.7,1180.28

In [22]:
agosto.shape #correto

(64, 9)

In [23]:
agosto.columns #espaços incorretos

Index([' ID ', 'Data Abertura', 'Data Fechamento', ' Tipo', 'Cliente ',
       'Responsavel', 'Prioridade', 'Horas ', 'Custo (R$)'],
      dtype='str')

In [24]:
agosto.info() #Tipo está com um espaçamento

<class 'pandas.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0    ID              64 non-null     int64
 1   Data Abertura    64 non-null     str
 2   Data Fechamento  64 non-null     str
 3    Tipo            64 non-null     str
 4   Cliente          64 non-null     str
 5   Responsavel      64 non-null     str
 6   Prioridade       64 non-null     str
 7   Horas            64 non-null     float64
 8   Custo (R$)       64 non-null     float64
dtypes: float64(2), int64(1), str(6)
memory usage: 8.3 KB

In [25]:
agosto.isna().sum() #correto

 ID                0
Data Abertura      0
Data Fechamento    0
 Tipo              0
Cliente            0
Responsavel        0
Prioridade         0
Horas              0
Custo (R$)         0
dtype: int64

In [26]:
agosto.duplicated().sum() #correto

np.int64(0)

In [27]:
agosto[" Tipo"].value_counts()
agosto.value_counts() #na coluna das horas tem um -10.4

 ID   Data Abertura  Data Fechamento   Tipo         Cliente           Responsavel    Prioridade  Horas   Custo (R$)
4000  20/08/2026     24/08/2026         Software     Beta Telecom     Diego Prado    Media        6.4    1676.29       1
4001  10/08/2026     13/08/2026       Telefonia     Ere Servicos      Carla Menezes  Media       -10.4   2390.06       1
4002  10/08/2026     16/08/2026         Acesso      Delta Industria   Diego Prado    Media        7.9    1224.46       1
4003  18/08/2026     20/08/2026       telefonia     Horizonte Bank    Diego Prado    Alta         0.9    1121.04       1
4004  07/08/2026     11/08/2026         Telefonia   Gama Saude        Elisa Fontes   Critica      0.7    1180.28       1
                                                                                                                      ..
4059  16/08/2026     21/08/2026       ACESSO         Delta Industria  Bruno Tavares  Baixa        7.5    1468.50       1
4060  21/08/2026     23/08/2026       Software      Cedro Varejo      Bruno Tavares  Media        5.0    2624.03       1
4061  18/08/2026     21/08/2026         Hardware     Cedro Varejo     Elisa Fontes   Critica      11.8   1347.03       1
4062  07/08/2026     07/08/2026         Software     Alfa Log         Carla Menezes  Critica      3.3    268.24        1
4063  09/08/2026     11/08/2026       Hardware       Beta Telecom     Carla Menezes  Critica      13.5   583.32        1
Name: count, Length: 64, dtype: int64

In [28]:
pd.set_option("display.float_format", "{:,.2f}".format)
agosto.describe()#valores muito altos

           ID   Horas    Custo (R$)
count    64.00   64.00        64.00
mean  4,031.50    6.92    80,099.64
std      18.62    4.75   432,424.69
min   4,000.00  -10.40       113.49
25%   4,015.75    4.50       780.67
50%   4,031.50    7.20     1,400.17
75%   4,047.25   10.25     2,329.49
max   4,063.00   14.00 3,132,690.00

In [29]:
agosto[" Tipo"].value_counts()

 Tipo
Telefonia       7
  Acesso        6
rede            6
Hardware        5
  Software      4
telefonia       4
acesso          4
  Hardware      4
  Telefonia     3
hardware        3
TELEFONIA       3
ACESSO          3
software        2
SOFTWARE        2
  Rede          2
HARDWARE        2
Software        2
REDE            1
Rede            1
Name: count, dtype: int64

In [30]:
agosto["Cliente "].value_counts()

Cliente
 Beta Telecom        5
Delta Industria      5
Ere Servicos         4
Cedro Varejo         4
Cedro Varejo         4
Ere Servicos         4
Gama Saude           3
Fenix Energia        3
 Gama Saude          3
Alfa Log             3
Delta Industria      3
Beta Telecom         3
 Alfa Log            3
Horizonte Bank       2
Beta Telecom         2
 Horizonte Bank      2
Gama Saude           2
 Delta Industria     2
 Cedro Varejo        2
Horizonte Bank       2
 Ere Servicos        2
Fenix Energia        1
Name: count, dtype: int64

2. Padronização e consolidação

In [ ]:
teste = pd.concat([maio, junho], ignore_index=True)
teste.shape

In [ ]:
teste.head(3)
teste.tail(3)

In [ ]:
maio.shape

In [ ]:
maio.columns=maio.columns.str.strip()
junho.columns=junho.columns.str.strip()
julho.columns=julho.columns.str.strip()
agosto.columns=agosto.columns.str.strip()

In [ ]:
agosto.columns #corrigiu agosto que estava tudo errado os espaços

In [ ]:
#corrigindo o nome das colunas
maio.columns

In [ ]:
junho.columns

In [ ]:
julho.columns

In [ ]:
agosto.columns

In [ ]:
agosto.columns #conferindo em algum mes para ver se a mudança foi feita corretamente

In [ ]:
#junho, julho e agosto devem ficar iguais o de maio
#criamos uma variavel chamada MAPA
MAPA={"ID":"id_chamado",
     'Data Abertura':"data_abertura",
     'Data Fechamento':'data_fechamento',
     "Tipo":"categoria",
     'Cliente':'cliente',
     'Responsavel':'tecnico',
      'Prioridade':'prioridade',
       'Horas': 'horas_gastas',
      'Custo (R$)':'custo_total'
     }
junho=junho.rename(columns=MAPA)
julho=julho.rename(columns=MAPA)  #aplica a variavel que criou
agosto=agosto.rename(columns=MAPA)

#resolvendo as datas em dia/mês/ano
maio["data_abertura"]   = pd.to_datetime(maio["data_abertura"],   format="%Y-%m-%d")
maio["data_fechamento"] = pd.to_datetime(maio["data_fechamento"], format="%Y-%m-%d")

junho["data_abertura"]   = pd.to_datetime(junho["data_abertura"],   format="%d/%m/%Y")
junho["data_fechamento"] = pd.to_datetime(junho["data_fechamento"], format="%d/%m/%Y")

julho["data_abertura"]   = pd.to_datetime(julho["data_abertura"],   format="%d/%m/%Y")
julho["data_fechamento"] = pd.to_datetime(julho["data_fechamento"], format="%d/%m/%Y")

agosto["data_abertura"]   = pd.to_datetime(agosto["data_abertura"],   format="%d/%m/%Y")
agosto["data_fechamento"] = pd.to_datetime(agosto["data_fechamento"], format="%d/%m/%Y")

In [ ]:
sorted(dados["data_abertura"].dt.month.unique())

In [ ]:
#resolvendo as virgulas que deveriam ser pontos
dados = pd.concat([maio, junho, julho, agosto], ignore_index=True) #pd.concat soma as linhas das tabelas de dentro do colchete
dados["custo_total"] = dados["custo_total"].astype(str).str.replace(",", ".").astype(float)
dados["horas_gastas"] = dados["horas_gastas"].astype(str).str.replace(",", ".").astype(float)
dados.shape #ignore_index=True eu nao entendi muito bem
dados.dtypes

3. Limpeza e conversão de tipos

In [ ]:
dados["categoria"].nunique() #O .nunique() conta quantos valores distintos existem na coluna. por exemplo espaços mal contados,letras maiusculas

In [ ]:
dados["cliente"].nunique()

In [ ]:
#tirando os espaços que ficaram mal colocados (ele nao resolve a letra maisucula)
dados.columns=dados.columns.str.strip()
dados["cliente"]=dados["cliente"].str.strip()
dados["categoria"]=dados["categoria"].str.strip()
dados["tecnico"]=dados["tecnico"].str.strip()
dados["prioridade"]=dados["prioridade"].str.strip()

#resolvendo letra maiuscula
dados["categoria"]=dados["categoria"].str.title() #esse .title() põe a primeira letra de cada palavra em maiuscula e o resto em minuscula.
dados["cliente"]=dados["cliente"].str.title()
#testando para ver se as letras maiusculas e minusculas ficaram certas (elas devem cair de 20 para , sabe-se disso pois maio é o jeito ideal, entao ele deve ficar 5 e 8)
dados["categoria"].nunique()

In [ ]:
#removendo as linhas que ficaram iguais
dados=dados.drop_duplicates(ignore_index=True) #ignore_index serve para renumerar de 0 a 318
dados.shape

In [ ]:
dados.duplicated().sum() #vendo se ainda tem duplicados

In [ ]:
#olhando estado atual
dados.isna().sum()

4. Regras de negócio

In [ ]:
dados["status"]="Fechado"
dados.loc[dados["data_fechamento"].isna(),"status"]=("Em aberto") #onde quero mexer (dados data_fechamento, isna(),qual quero mudar(status), oque quero mudar para ("Em aberto"))

In [ ]:
dados.loc[dados["tecnico"].isna(),"tecnico"]=("Não atribuído")

In [ ]:
dados.loc[dados["custo_total"].isna(),"custo_total"]=dados["custo_total"].median()

In [ ]:
#conferindo
dados.isna().sum()

In [ ]:
#resolvendo as horas negativas
dados[dados["horas_gastas"]<0]

In [ ]:
#acredito que o problema tenha sido a digitação, entao vamos tirar essas horas negativas
dados.loc[dados["horas_gastas"]<0,"horas_gastas"]=dados["horas_gastas"].abs() #ou pode por dados["horas_gastas"]=dados["horas_gastas"].abs()

#conferindo
dados["horas_gastas"].min()

In [ ]:
#conferindo dnv
dados[dados["horas_gastas"]<0]

In [ ]:
#resolvendo a parte dos custos altissimos
dados[dados["custo_total"]>100000]

In [ ]:
dados[dados["custo_total"]<=100000]["custo_total"].describe() #faixa normal dos outros 316 chamados

In [ ]:
#os valores se dividir por 1000 fica ok
dados.loc[dados["custo_total"]>10000,"custo_total"]=dados["custo_total"]/ 1000
dados["custo_total"].max()
# custo_total: 3 chamados com valores absurdos (R$ 419.960, R$ 1.483.500,
# R$ 3.132.690) contra uma faixa legitima de R$ 83 a R$ 3.181.
# Dividindo os tres por 1000, todos caem dentro da faixa normal E resultam
# em valores com exatamente 2 casas decimais, como todos os outros custos.
# Isso indica erro sistematico de digitacao (tres zeros a mais), nao valor
# invalido. Por isso corrigi o fator em vez de substituir pela mediana.
#
# LIMITACAO: o corte em 10.000 e fixo. Se a operacao passar a ter chamados
# legitimamente caros, esse limite precisa ser revisto

In [ ]:
(dados["custo_total"] > 10000).sum()

In [ ]:
### final
dados.shape

In [ ]:
dados.isna().sum()

In [ ]:
dados.duplicated().sum()

In [ ]:
dados["categoria"].value_counts()

In [ ]:
dados["cliente"].nunique()

In [ ]:
dados.describe()

In [ ]:
#criando dias_para_resolver
dados["dias_para_resolver"] = (dados["data_fechamento"] - dados["data_abertura"]).dt.days #esse dt.days extrai o numero de dias de duração
#Os 5 chamados em aberto vão ficar com NaN nessa coluna — e isso está certo: não dá pra calcular quanto tempo levou algo que não terminou.
dados["dias_para_resolver"].describe()

5. Resumos e KPIs

In [ ]:
dados.groupby("categoria")["custo_total"].sum() #primeira linha do relatorio

In [ ]:
#agg serve para agrupar mais de um
resumo_categoria= dados.groupby("categoria").agg(  #estrutura do .agg(): nome_da_coluna_nova=("coluna_de_onde_vem","que_conta_devo_fazer")
    chamados=("id_chamado","count"),
    horas_totais=("horas_gastas","sum"),
    custo_total=("custo_total","sum")
)
resumo_categoria

In [ ]:
dados["mes"] = dados["data_abertura"].dt.strftime("%Y-%m")
dados["mes"].value_counts()

In [ ]:
resumo_mes = dados.groupby("mes").agg(
    chamados     = ("id_chamado",   "count"),
    horas_totais = ("horas_gastas", "sum"),
    custo_total  = ("custo_total",  "sum"),
)
resumo_mes

In [ ]:
dados.groupby("prioridade")["dias_para_resolver"].mean()
resumo_prioridade = dados.groupby("prioridade").agg(
    chamados   = ("id_chamado",         "count"),
    dias_medio = ("dias_para_resolver", "mean"),
)
resumo_prioridade

6. Exportação

In [ ]:
with pd.ExcelWriter("relatorio_consolidado.xlsx", engine="openpyxl") as writer:
    dados.to_excel(writer, sheet_name="dados_limpos", index=False)
    resumo_categoria.to_excel(writer, sheet_name="resumo_categoria")
    resumo_mes.to_excel(writer, sheet_name="resumo_mes")
    resumo_prioridade.to_excel(writer, sheet_name="resumo_prioridade")